require("dotenv").config();
const mongoose = require("mongoose");
const Bug = require("./models/Bug");

// Demo seed data for the Bug & Error Dashboard.
// All data below is fake/sample data for portfolio demonstration only.
const sampleBugs = [
  {
    endpoint: "/api/v1/auth/refresh",
    message: "Token refresh failed (403 Forbidden)",
    source: "Rollbar",
    priority: "P0",
    status: "In progress",
    count: 312,
    method: "POST",
    errorType: "AuthError",
    ticketId: "BUG-101",
    ticketStatus: "In progress",
    notes: "Working on it",
  },
  {
    endpoint: "/api/v1/payments/charge",
    message: "NullPointerException in PaymentProcessor.charge()",
    source: "Rollbar",
    priority: "P0",
    status: "New",
    count: 47,
    method: "POST",
    errorType: "NullPointerException",
    ticketId: "BUG-102",
    ticketStatus: "Open",
  },
  {
    endpoint: "/api/v1/orders/summary",
    message: "Network Error: request timed out after 30s",
    source: "PostHog",
    priority: "P1",
    status: "New",
    count: 188,
    method: "GET",
    errorType: "NetworkError",
    browser: "Chrome 125",
  },
  {
    endpoint: "/api/v1/inventory/sync",
    message: "IncorrectResultSizeDataAccessException: query returned 2 results, expected 1",
    source: "Rollbar",
    priority: "P1",
    status: "In progress",
    count: 994,
    method: "GET",
    errorType: "DataAccessException",
    ticketId: "BUG-104",
    ticketStatus: "In progress",
    notes: "Known issue",
  },
  {
    endpoint: "/api/v1/users/me",
    message: "Network Error: 401 Unauthorized",
    source: "PostHog",
    priority: "P2",
    status: "Done",
    count: 23,
    method: "GET",
    errorType: "NetworkError",
    resolvedAt: new Date("2026-06-20T10:30:00Z"),
    ticketId: "BUG-105",
    ticketStatus: "Closed",
    notes: "Cannot reproduce",
  },
  {
    endpoint: "/api/v1/projects/create",
    message: "500 Internal Server Error: duplicate budget category code",
    source: "Rollbar",
    priority: "P1",
    status: "Done",
    count: 14,
    method: "POST",
    errorType: "ServerError",
    resolvedAt: new Date("2026-06-22T14:00:00Z"),
    ticketId: "BUG-106",
    ticketStatus: "Closed",
  },
  {
    endpoint: "/api/v1/reports/export",
    message: "OutOfMemoryError: Java heap space during CSV export",
    source: "Rollbar",
    priority: "P2",
    status: "New",
    count: 8,
    method: "GET",
    errorType: "OutOfMemoryError",
  },
  {
    endpoint: "/api/v1/dashboard/widgets",
    message: "ClassCastException: Integer cannot be cast to Double",
    source: "Rollbar",
    priority: "P1",
    status: "In progress",
    count: 56,
    method: "GET",
    errorType: "ClassCastException",
    ticketId: "BUG-108",
    ticketStatus: "In progress",
    notes: "Need more info",
  },
  {
    endpoint: "/api/v1/notifications/poll",
    message: "Network Error: ERR_CONNECTION_REFUSED",
    source: "PostHog",
    priority: "P3",
    status: "New",
    count: 4,
    method: "GET",
    errorType: "NetworkError",
    browser: "Safari 17",
  },
  {
    endpoint: "/api/v1/files/upload",
    message: "MaxUploadSizeExceededException: file too large (limit 10MB)",
    source: "Rollbar",
    priority: "P2",
    status: "Done",
    count: 31,
    method: "POST",
    errorType: "ValidationError",
    resolvedAt: new Date("2026-06-18T09:15:00Z"),
    ticketId: "BUG-110",
    ticketStatus: "Closed",
  },
  {
    endpoint: "/api/v1/search/query",
    message: "QueryTimeoutException: slow query exceeded 5000ms",
    source: "Rollbar",
    priority: "P2",
    status: "New",
    count: 67,
    method: "GET",
    errorType: "TimeoutException",
  },
  {
    endpoint: "/api/v1/billing/invoice",
    message: "Network Error: 502 Bad Gateway",
    source: "PostHog",
    priority: "P1",
    status: "New",
    count: 120,
    method: "GET",
    errorType: "NetworkError",
    browser: "Edge 124",
  },
  {
    endpoint: "/api/v1/auth/login",
    message: "RateLimitExceededException: too many login attempts",
    source: "Rollbar",
    priority: "P2",
    status: "In progress",
    count: 41,
    method: "POST",
    errorType: "RateLimitError",
    ticketId: "BUG-113",
    ticketStatus: "In progress",
  },
  {
    endpoint: "/api/v1/webhooks/receive",
    message: "JsonParseException: unexpected token at position 142",
    source: "Rollbar",
    priority: "P3",
    status: "Done",
    count: 6,
    method: "POST",
    errorType: "JsonParseException",
    resolvedAt: new Date("2026-06-15T16:45:00Z"),
    ticketId: "BUG-114",
    ticketStatus: "Closed",
  },
  {
    endpoint: "/api/v1/inventory/update",
    message: "OptimisticLockingFailureException: row was updated by another transaction",
    source: "Rollbar",
    priority: "P1",
    status: "New",
    count: 89,
    method: "PATCH",
    errorType: "ConcurrencyError",
  },
  {
    endpoint: "/api/v1/analytics/track",
    message: "Network Error: CORS policy blocked request",
    source: "PostHog",
    priority: "P3",
    status: "New",
    count: 15,
    method: "POST",
    errorType: "NetworkError",
    browser: "Firefox 127",
  },
  {
    endpoint: "/api/v1/orders/cancel",
    message: "IllegalStateException: order already shipped, cannot cancel",
    source: "Rollbar",
    priority: "P2",
    status: "Done",
    count: 19,
    method: "POST",
    errorType: "IllegalStateException",
    resolvedAt: new Date("2026-06-23T11:20:00Z"),
    ticketId: "BUG-117",
    ticketStatus: "Closed",
    notes: "Working on it",
  },
  {
    endpoint: "/api/v1/email/send",
    message: "SMTPConnectionException: connection to mail server timed out",
    source: "Rollbar",
    priority: "P1",
    status: "In progress",
    count: 73,
    method: "POST",
    errorType: "SMTPException",
    ticketId: "BUG-118",
    ticketStatus: "In progress",
  },
  {
    endpoint: "/api/v1/profile/avatar",
    message: "Network Error: 404 Not Found",
    source: "PostHog",
    priority: "P3",
    status: "New",
    count: 9,
    method: "GET",
    errorType: "NetworkError",
    browser: "Chrome 126",
  },
  {
    endpoint: "/api/v1/subscriptions/renew",
    message: "PaymentDeclinedException: card declined by issuer",
    source: "Rollbar",
    priority: "P1",
    status: "New",
    count: 52,
    method: "POST",
    errorType: "PaymentException",
  },
  {
    endpoint: "/api/v1/settings/save",
    message: "ValidationException: required field 'timezone' is missing",
    source: "Rollbar",
    priority: "P3",
    status: "Done",
    count: 12,
    method: "PUT",
    errorType: "ValidationError",
    resolvedAt: new Date("2026-06-19T13:00:00Z"),
    ticketId: "BUG-121",
    ticketStatus: "Closed",
  },
  {
    endpoint: "/api/v1/reports/generate",
    message: "Network Error: 503 Service Unavailable",
    source: "PostHog",
    priority: "P2",
    status: "New",
    count: 34,
    method: "GET",
    errorType: "NetworkError",
    browser: "Chrome 125",
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to database. Seeding demo data...");

    // Clear existing bugs so the demo always starts clean
    await Bug.deleteMany({});
    console.log("Cleared old data.");

    await Bug.insertMany(sampleBugs);
    console.log(`Done. Inserted ${sampleBugs.length} sample bugs.`);
  } catch (error) {
    console.log("Error:", error.message);
  } finally {
    await mongoose.disconnect();
    console.log("Disconnected.");
  }
}

seed();